name: Deployment Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    #  Cancela el deploy hecho anteriormente si continua corriendo
    - name: Cancel Previous Redundant Bulds
      uses: styfle/cancel-workflow-action
      with:
        access_token: ${{ github.token }}
    #  Obtiene el repositorio en el ultimo commit
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Intstala ambiente node  
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci --no-audit --no-fund --no-optional
    - name: Lint
      run: npm run lint
    - name: Build App
      run: npm run build
    - name: Unit test
      run: npm run test
    # - name: Run App
    #   run: npm run start
    - name: Deploy to Heroku
      if: ${{ github.event_name == 'push' }}
      uses: AkhileshNS/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_APP_EMAIL}}
        healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
        checkstring: "ok"
        rollbackonhealthcheckfailed: true



