name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    #  Obtiene el repositorio en el ultimo commit
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Intstala ambiente node  
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci --no-audit --no-fund --no-optional
    - name: Lint
      run: npm run lint
    - name: Build App
      run: npm run build
    - name: Unit test
      run: npm run test
    - name: Run App
      run: npm run start
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_APP_EMAIL}}



