name: Deployment Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:

  #  Cancela el deploy hecho anteriormente si continua corriendo
  avoid_redundancy:
    name: Cancel builds
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  lint: 
    name: Run linter
    runs-on: ubuntu-latest
    steps:
    #  Obtiene el repositorio en el ultimo commit
    - name: Checkout last commit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Intstala ambiente node
    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci --no-audit --no-fund --no-optional
    - name: Lint
      run: npm run lint

  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    #  Obtiene el repositorio en el ultimo commit
    - name: Checkout last commit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Intstala ambiente node
    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci --no-audit --no-fund --no-optional
    - name: Unit test
      run: npm run test

  build: 
    needs: [unit_tests, lint]
    runs-on: ubuntu-latest
    name: Build app
    steps:
    #  Obtiene el repositorio en el ultimo commit
    - name: Checkout last commit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Intstala ambiente node
    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci --no-audit --no-fund --no-optional
    - name: Build App
      run: npm run build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: dist
        path: dist
  
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    #  Obtiene el repositorio en el ultimo commit
    - name: Checkout last commit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Deploy to Heroku
      if: ${{ github.event_name == 'push' }}
      uses: AkhileshNS/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_APP_EMAIL}}
        healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
        checkstring: "ok"
        rollbackonhealthcheckfailed: true



